# Generated by Django 3.1.5 on 2021-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=50, verbose_name='Project Name')),
                ('PDescription', models.TextField(verbose_name='Project description')),
                ('PUrl', models.URLField(verbose_name='Project URL')),
                ('PImage', models.ImageField(upload_to=None, verbose_name='Project Image')),
            ],
        ),
    ]
