# Generated by Django 3.1.5 on 2021-02-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0003_auto_20210208_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='Image',
        ),
    ]
