# Generated by Django 3.1.5 on 2021-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='Skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='Technologies',
            field=models.ManyToManyField(to='Skills.Technology'),
        ),
    ]
