# Generated by Django 3.1.5 on 2021-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portofolio', '0003_auto_20210208_1030'),
        ('Skills', '0002_auto_20210203_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('Image', models.ImageField(upload_to='media/skills', verbose_name='Skill Image')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='Technologies',
        ),
        migrations.AddField(
            model_name='skill',
            name='Percentage',
            field=models.IntegerField(default=True, verbose_name='Precentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='speciality',
            name='Skills',
            field=models.ManyToManyField(to='Skills.Skill'),
        ),
    ]
