# Generated by Django 3.1.5 on 2021-01-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
        ('Portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='PDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='PImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='PName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='PUrl',
            new_name='Url',
        ),
        migrations.AddField(
            model_name='project',
            name='Technologies',
            field=models.ManyToManyField(to='Skills.Technology'),
        ),
    ]
