# Generated by Django 3.1.5 on 2021-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portofolio', '0002_auto_20210127_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('TextColor', models.CharField(max_length=50, verbose_name='Text Color')),
                ('BackgroundColor', models.CharField(max_length=50, verbose_name='Background Color')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='Technologies',
            field=models.ManyToManyField(to='Portofolio.Technology'),
        ),
    ]
