# Generated by Django 3.1.5 on 2021-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portofolio', '0003_auto_20210208_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(verbose_name='Project Description'),
        ),
    ]
